//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flowersplantationEntities8 : DbContext
    {
        public flowersplantationEntities8()
            : base("name=flowersplantationEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flowerimage> flowerimages { get; set; }
        public virtual DbSet<myflower> myflowers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
