//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flowersplantationEntities51 : DbContext
    {
        public flowersplantationEntities51()
            : base("name=flowersplantationEntities51")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<favoriteflower> favoriteflowers { get; set; }
        public virtual DbSet<flowercity> flowercities { get; set; }
        public virtual DbSet<flowercolor> flowercolors { get; set; }
        public virtual DbSet<flower> flowers { get; set; }
        public virtual DbSet<friend> friends { get; set; }
        public virtual DbSet<nursery> nurseries { get; set; }
        public virtual DbSet<nurserystock> nurserystocks { get; set; }
        public virtual DbSet<planflower> planflowers { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<userrequest> userrequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
