//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myflower
    {
        public string name { get; set; }
        public string color { get; set; }
        public string month { get; set; }
        public string season { get; set; }
        public string growtime { get; set; }
        public string height { get; set; }
        public string category { get; set; }
        public string shape { get; set; }
        public string fragrance { get; set; }
        public string lifetime { get; set; }
        public string altitude { get; set; }
        public string area { get; set; }
        public int id { get; set; }
    }
}
