//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nursery
    {
        public int nid { get; set; }
        public string nname { get; set; }
        public string naddress { get; set; }
        public string ncontact { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
