//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nurserystock
    {
        public Nullable<int> nid { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> flowerquantity { get; set; }
        public int id { get; set; }
    }
}
